config/routes.rb
CsvExportTest::Application.routes.draw do

  root 'products#index'
  resources 'products', only: :index
  

end

app/models/manufacture.rb
class Manufacture < ActiveRecord::Base
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :manufacture

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |product|
        csv << product.csv_column_values
      end
    end
  end

  def self.csv_column_names
    ["ID", "商品名", "値段", "発売日", "製造元"]
  end

  def csv_column_values
    [id, name, price, released_on, manufacture.name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # def index
  # end

  def index
    @products = Product.includes(:manufacture)

    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls { send_data @products.to_csv(col_sep: "\t") }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvExportTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>値段</th>
      <th>発売日</th>
      <th>製造元</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.released_on %></td>
        <td><%= product.manufacture.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %>
  |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>